##########################################################################
##  v      #                  The Coq Proof Assistant                   ##
## <O___,, # CNRS-Ecole Polytechnique-INRIA Futurs-Universite Paris Sud ##
##   \VV/  #                                                            ##
##    //   #   Makefile automagically generated by coq_makefile V8.2    ##
##########################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS:=
COQLIBS:= -R . FSSecModel
COQDOCLIBS:=-R . FSSecModel

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB:=$(shell $(CAMLBIN)camlp5 -where 2> /dev/null || $(CAMLBIN)camlp4 -where)
CAMLP4:=$(notdir $(CAMLP4LIB))
COQSRC:=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS:=$(OCAMLLIBS) $(COQSRC)
OPT:=
COQFLAGS:=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC:=$(COQBIN)coqc
COQDEP:=$(COQBIN)coqdep -c
GALLINA:=$(COQBIN)gallina
COQDOC:=$(COQBIN)coqdoc
CAMLC:=$(CAMLBIN)ocamlc -rectypes -c
CAMLOPTC:=$(CAMLBIN)ocamlopt -c
CAMLLINK:=$(CAMLBIN)ocamlc
CAMLOPTLINK:=$(CAMLBIN)ocamlopt
GRAMMARS:=grammar.cma
CAMLP4EXTEND:=pa_extend.cmo pa_macro.cmo q_MLast.cmo
PP:=-pp "$(CAMLBIN)$(CAMLP4)o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES:=ListSet.v\
  ListFunctions.v\
  SFSstate.v\
  InitialState.v\
  sscstat.v\
  setACLdata.v\
  DACandMAC.v\
  mkdir.v\
  create.v\
  chmod.v\
  write.v\
  unlink.v\
  stat.v\
  rmdir.v\
  readdir.v\
  owner_close.v\
  oscstat.v\
  open.v\
  close.v\
  chsubsc.v\
  chown.v\
  chobjsc.v\
  addUsrGrpToAcl.v\
  aclstat.v\
  read.v\
  delUsrGrpFromAcl.v\
  TransFunc.v\
  ModelProperties.v\
  AuxiliaryLemmas.v\
  aclstatIsSecure.v\
  addUsrGrpToAclIsSecure.v\
  chmodIsSecure.v\
  chobjscIsSecure.v\
  chownIsSecure.v\
  chsubscIsSecure.v\
  closeIsSecure.v\
  createIsSecure.v\
  delUsrGrpFromAclIsSecure.v\
  mkdirIsSecure.v\
  openIsSecure.v\
  oscstatIsSecure.v\
  owner_closeIsSecure.v\
  readdirIsSecure.v\
  readIsSecure.v\
  rmdirIsSecure.v\
  sscstatIsSecure.v\
  statIsSecure.v\
  unlinkIsSecure.v\
  writeIsSecure.v\
  ModelLemmas.v
VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

all: ListSet.vo\
  ListFunctions.vo\
  SFSstate.vo\
  InitialState.vo\
  sscstat.vo\
  setACLdata.vo\
  DACandMAC.vo\
  mkdir.vo\
  create.vo\
  chmod.vo\
  write.vo\
  unlink.vo\
  stat.vo\
  rmdir.vo\
  readdir.vo\
  owner_close.vo\
  oscstat.vo\
  open.vo\
  close.vo\
  chsubsc.vo\
  chown.vo\
  chobjsc.vo\
  addUsrGrpToAcl.vo\
  aclstat.vo\
  read.vo\
  delUsrGrpFromAcl.vo\
  TransFunc.vo\
  ModelProperties.vo\
  AuxiliaryLemmas.vo\
  aclstatIsSecure.vo\
  addUsrGrpToAclIsSecure.vo\
  chmodIsSecure.vo\
  chobjscIsSecure.vo\
  chownIsSecure.vo\
  chsubscIsSecure.vo\
  closeIsSecure.vo\
  createIsSecure.vo\
  delUsrGrpFromAclIsSecure.vo\
  mkdirIsSecure.vo\
  openIsSecure.vo\
  oscstatIsSecure.vo\
  owner_closeIsSecure.vo\
  readdirIsSecure.vo\
  readIsSecure.vo\
  rmdirIsSecure.vo\
  sscstatIsSecure.vo\
  statIsSecure.vo\
  unlinkIsSecure.vo\
  writeIsSecure.vo\
  ModelLemmas.vo

spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

.SUFFIXES: .v .vo .vi .g .html .tex .g.tex .g.html

%.vo %.glob: %.v
	$(COQC) -dump-glob $*.glob $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob  -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob -html -g $< -o $@

%.v.d.raw: %.v
	$(COQDEP) -slash $(COQLIBS) "$<" > "$@"\
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

%.v.d: %.v.d.raw
	$(HIDE)sed 's/\(.*\)\.vo[[:space:]]*:/\1.vo \1.glob:/' < "$<" > "$@" \
	  || ( RV=$$?; rm -f "$@"; exit $${RV} )

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f $(VOFILES) `$(COQC) -where`/user-contrib

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


clean:
	rm -f *.cmo *.cmi *.cmx *.o $(VOFILES) $(VIFILES) $(GFILES) *~
	rm -f all.ps all-gal.ps all.glob $(VFILES:.v=.glob) $(HTMLFILES) $(GHTMLFILES) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) $(VFILES:.v=.v.d)
	- rm -rf html

archclean:
	rm -f *.cmx *.o


-include $(VFILES:.v=.v.d)
.SECONDARY: $(VFILES:.v=.v.d)

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

